// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listClips: (source: string | null, contentType: string | null, limit: number | null) => typedError<LocalClip[], string>(__TAURI_INVOKE("list_clips", { source, contentType, limit })),
	searchClips: (query: string, limit: number | null) => typedError<LocalClip[], string>(__TAURI_INVOKE("search_clips", { query, limit })),
	getSources: () => typedError<SourceInfo[], string>(__TAURI_INVOKE("get_sources")),
	deleteClip: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_clip", { id })),
	getClipCount: () => typedError<number, string>(__TAURI_INVOKE("get_clip_count")),
	getConfigInfo: () => __TAURI_INVOKE<ConfigInfo>("get_config_info"),
	getSourceAutoCopy: (source: string) => typedError<boolean, string>(__TAURI_INVOKE("get_source_auto_copy", { source })),
	setSourceAutoCopy: (source: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_source_auto_copy", { source, enabled })),
	getAllSourceSettings: () => typedError<SourceSetting[], string>(__TAURI_INVOKE("get_all_source_settings")),
	copyClipToClipboard: (content: string) => typedError<null, string>(__TAURI_INVOKE("copy_clip_to_clipboard", { content })),
	copyImageToClipboard: (mediaPath: string) => typedError<null, string>(__TAURI_INVOKE("copy_image_to_clipboard", { mediaPath })),
	listDevices: () => typedError<DeviceInfo[], string>(__TAURI_INVOKE("list_devices")),
	setDeviceNickname: (deviceId: string, nickname: string) => typedError<null, string>(__TAURI_INVOKE("set_device_nickname", { deviceId, nickname })),
	revokeDevice: (deviceId: string) => typedError<null, string>(__TAURI_INVOKE("revoke_device", { deviceId })),
	getExcludedApps: () => typedError<string[], string>(__TAURI_INVOKE("get_excluded_apps")),
	setExcludedApps: (apps: string[]) => typedError<null, string>(__TAURI_INVOKE("set_excluded_apps", { apps })),
	getRetentionConfig: () => typedError<RetentionConfig, string>(__TAURI_INVOKE("get_retention_config")),
	setRetentionConfig: (localDays: number, remoteDays: number) => typedError<null, string>(__TAURI_INVOKE("set_retention_config", { localDays, remoteDays })),
	/**
	 *  Return the number of clips that would be deleted if `local_retention_days`
	 *  were set to `days` right now. Backs the Settings-pane retroactive-purge
	 *  confirmation dialog. Uses `Database::count_clips_before`.
	 * 
	 *  `days` is clamped to `[MIN_RETENTION_DAYS, MAX_RETENTION_DAYS]` (T-06-02):
	 *  `365 * 86_400 = 31_536_000` stays well within `i64`, so no overflow is
	 *  possible within bounds.
	 */
	previewRetentionChange: (days: number) => typedError<number, string>(__TAURI_INVOKE("preview_retention_change", { days })),
	/**
	 *  Wipe every clip row + cascade-delete media files. Returns the number of
	 *  rows deleted. Used by the "Clear local history" Settings button (PRV-03).
	 */
	clearLocalHistory: () => typedError<number, string>(__TAURI_INVOKE("clear_local_history")),
	saveConfig: (relayUrl: string, token: string) => typedError<null, string>(__TAURI_INVOKE("save_config", { relayUrl, token })),
	getWsStatus: () => __TAURI_INVOKE<string>("get_ws_status"),
	getGlobalShortcut: () => typedError<string, string>(__TAURI_INVOKE("get_global_shortcut")),
	setGlobalShortcut: (shortcut: string) => typedError<null, string>(__TAURI_INVOKE("set_global_shortcut", { shortcut })),
	// Returns the current AuthState. Used by AuthProvider's initial fetch in React.
	getAuthState: () => __TAURI_INVOKE<AuthState>("get_auth_state"),
	/**
	 *  sign_in — opens the relay's browser auth page in the system browser.
	 * 
	 *  Phase 4 flow:
	 *    1. Transitions to Authenticating{SigningIn}
	 *    2. Opens {relay_url}/auth/browser in the system browser via tauri_plugin_opener
	 *    3. Returns immediately — the deep-link callback (cinch://auth/callback) handles
	 *       credential write + state transition when the browser redirects back.
	 */
	signIn: (relayUrl: string) => typedError<null, string>(__TAURI_INVOKE("sign_in", { relayUrl })),
	/**
	 *  sign_out — calls POST /auth/device/revoke (best-effort), wipes credentials, transitions to LocalOnly.
	 *  Mirrors the CLI `auth logout` D-10 behavior.
	 */
	signOut: () => typedError<null, string>(__TAURI_INVOKE("sign_out")),
	/**
	 *  retry_auth — bypasses ErrorRecoverable.retry_after_ms and re-attempts the last failing operation.
	 *  For Phase 2 plumbing: resets to LocalOnly and lets the user re-invoke sign_in.
	 *  Phase 3+ will store the last-attempted operation and retry it in place.
	 */
	retryAuth: () => typedError<null, string>(__TAURI_INVOKE("retry_auth")),
	/**
	 *  handle_deeplink — Tauri command for React to invoke when it receives a deep-link URL
	 *  via getCurrent() (cold-start case) or onOpenUrl (fallback for JS-side handling).
	 * 
	 *  Parses the URL, extracts auth params, writes credentials, transitions state,
	 *  and spawns WS client.
	 */
	handleDeeplink: (url: string) => typedError<null, string>(__TAURI_INVOKE("handle_deeplink", { url })),
};

/** Events */
export const events = {
	authStateChanged: makeEvent<AuthStateChanged>("auth-state-changed"),
	clipDeleted: makeEvent<ClipDeleted>("clip-deleted"),
	clipReceived: makeEvent<ClipReceived>("clip-received"),
	imageDownloadComplete: makeEvent<ImageDownloadComplete>("image-download-complete"),
	imageDownloadFailed: makeEvent<ImageDownloadFailed>("image-download-failed"),
	newSourceDetected: makeEvent<NewSourceDetected>("new-source-detected"),
	wsStatus: makeEvent<WsStatus>("ws-status"),
};

/* Types */
export type AuthErrorReason = { kind: "RelayUnreachable" } | { kind: "KeyringUnavailable" } | { kind: "NetworkDown" } | { kind: "InvalidPairToken" };

export type AuthProgress = { kind: "SigningIn" } | { kind: "Pairing" } | { kind: "RotatingToken" };

export type AuthState = { variant: "LocalOnly" } | { variant: "Authenticating"; payload: {
	progress: AuthProgress,
} } | { variant: "Authenticated"; payload: {
	user_id: string,
	device_id: string,
	hostname: string,
	relay_url: string,
} } | { variant: "ErrorRecoverable"; payload: {
	reason: AuthErrorReason,
	retry_after_ms: number | null,
} };

export type AuthStateChanged = AuthState;

export type ClipDeleted = string;

export type ClipReceived = LocalClip;

export type ConfigInfo = {
	relay_url: string,
	user_id: string,
	hostname: string,
};

export type DeviceInfo = {
	id: string,
	hostname: string,
	source_key: string,
	clip_count: number,
	paired_at: string,
	last_push_at: string | null,
	online: boolean,
	nickname?: string | null,
};

export type ImageDownloadComplete = string;

export type ImageDownloadFailed = string;

export type LocalClip = {
	id: string,
	user_id: string,
	content: string,
	content_type: string,
	source: string,
	label: string,
	byte_size: number,
	media_path: string | null,
	created_at: number,
	ttl: number,
	synced: boolean,
};

export type NewSourceDetected = string;

/**
 *  Settings-pane retention config (plan 01-06).
 * 
 *  `local_days` = rolling window for the local SQLite cache.
 *  `remote_days` = rolling window for relay-stored clips.
 *  Default is 30 days per D-05; clamp range is `[7, 365]` per V5.
 */
export type RetentionConfig = {
	local_days: number,
	remote_days: number,
};

export type SourceInfo = {
	source: string,
	clip_count: number,
	last_seen: number,
};

export type SourceSetting = {
	source: string,
	auto_copy: boolean,
};

export type WsStatus = string;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

