// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listClips: (source: string | null, contentType: string | null, limit: number | null) => typedError<LocalClip[], string>(__TAURI_INVOKE("list_clips", { source, contentType, limit })),
	listPinnedClips: () => typedError<LocalClip[], string>(__TAURI_INVOKE("list_pinned_clips")),
	pinClip: (id: string, note: string | null) => typedError<null, string>(__TAURI_INVOKE("pin_clip", { id, note })),
	unpinClip: (id: string) => typedError<null, string>(__TAURI_INVOKE("unpin_clip", { id })),
	searchClips: (query: string, limit: number | null) => typedError<LocalClip[], string>(__TAURI_INVOKE("search_clips", { query, limit })),
	getSources: () => typedError<SourceInfo[], string>(__TAURI_INVOKE("get_sources")),
	deleteClip: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_clip", { id })),
	getClipCount: () => typedError<number, string>(__TAURI_INVOKE("get_clip_count")),
	getConfigInfo: () => __TAURI_INVOKE<ConfigInfo>("get_config_info"),
	getSourceAutoCopy: (source: string) => typedError<boolean, string>(__TAURI_INVOKE("get_source_auto_copy", { source })),
	setSourceAutoCopy: (source: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_source_auto_copy", { source, enabled })),
	getAllSourceSettings: () => typedError<SourceSetting[], string>(__TAURI_INVOKE("get_all_source_settings")),
	getSourceAlertEnabled: (source: string) => typedError<boolean, string>(__TAURI_INVOKE("get_source_alert_enabled", { source })),
	setSourceAlertEnabled: (source: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_source_alert_enabled", { source, enabled })),
	getAllSourceAlertSettings: () => typedError<SourceAlertSetting[], string>(__TAURI_INVOKE("get_all_source_alert_settings")),
	markClipCopied: (id: string) => typedError<null, string>(__TAURI_INVOKE("mark_clip_copied", { id })),
	copyClipToClipboard: (content: string) => typedError<null, string>(__TAURI_INVOKE("copy_clip_to_clipboard", { content })),
	copyImageToClipboard: (mediaPath: string) => typedError<null, string>(__TAURI_INVOKE("copy_image_to_clipboard", { mediaPath })),
	/**
	 *  Restore focus to the app that was frontmost before Cinch was shown, then hide the
	 *  Cinch window. On non-macOS platforms this simply hides the window.
	 */
	focusPreviousApp: () => typedError<null, string>(__TAURI_INVOKE("focus_previous_app")),
	listDevices: () => typedError<Device[], string>(__TAURI_INVOKE("list_devices")),
	setDeviceNickname: (deviceId: string, nickname: string) => typedError<null, string>(__TAURI_INVOKE("set_device_nickname", { deviceId, nickname })),
	revokeDevice: (deviceId: string) => typedError<null, string>(__TAURI_INVOKE("revoke_device", { deviceId })),
	getExcludedApps: () => typedError<string[], string>(__TAURI_INVOKE("get_excluded_apps")),
	setExcludedApps: (apps: string[]) => typedError<null, string>(__TAURI_INVOKE("set_excluded_apps", { apps })),
	getRetentionConfig: () => typedError<RetentionConfig, string>(__TAURI_INVOKE("get_retention_config")),
	setRetentionConfig: (localDays: number, remoteDays: number) => typedError<null, string>(__TAURI_INVOKE("set_retention_config", { localDays, remoteDays })),
	/**
	 *  Return the number of clips that would be deleted if `local_retention_days`
	 *  were set to `days` right now. Backs the Settings-pane retroactive-purge
	 *  confirmation dialog. Uses `Database::count_clips_before`.
	 * 
	 *  `days` is clamped to `[MIN_RETENTION_DAYS, MAX_RETENTION_DAYS]` (T-06-02):
	 *  `365 * 86_400 = 31_536_000` stays well within `i64`, so no overflow is
	 *  possible within bounds.
	 */
	previewRetentionChange: (days: number) => typedError<number, string>(__TAURI_INVOKE("preview_retention_change", { days })),
	/**
	 *  Wipe every clip row + cascade-delete media files. Returns the number of
	 *  rows deleted. Used by the "Clear local history" Settings button (PRV-03).
	 */
	clearLocalHistory: () => typedError<number, string>(__TAURI_INVOKE("clear_local_history")),
	saveConfig: (relayUrl: string, token: string) => typedError<null, string>(__TAURI_INVOKE("save_config", { relayUrl, token })),
	getWsStatus: () => __TAURI_INVOKE<string>("get_ws_status"),
	getGlobalShortcut: () => typedError<string, string>(__TAURI_INVOKE("get_global_shortcut")),
	setGlobalShortcut: (shortcut: string) => typedError<null, string>(__TAURI_INVOKE("set_global_shortcut", { shortcut })),
	// Returns the current AuthState. Used by AuthProvider's initial fetch in React.
	getAuthState: () => __TAURI_INVOKE<AuthState>("get_auth_state"),
	/**
	 *  sign_in — browser-based sign-in using device-code polling.
	 * 
	 *  Flow (deep-link-independent):
	 *    1. Transitions to Authenticating{SigningIn}
	 *    2. POSTs to {relay_url}/auth/device-code to get a device_code + verification_uri
	 *    3. Opens verification_uri in the system browser (includes device_code so OAuth
	 *       providers show the right page and the relay can complete the flow)
	 *    4. Returns immediately — a background tokio task polls
	 *       GET {relay_url}/auth/device-code/poll?code={device_code} every 3 seconds
	 *    5. When status == "complete", writes credentials and transitions to Authenticated
	 * 
	 *  The existing cinch://auth/callback deep-link handler in lib.rs still fires as a
	 *  secondary path (legacy self-host servers that skip the device-code completion step).
	 */
	signIn: (relayUrl: string, provider: string | null) => typedError<null, string>(__TAURI_INVOKE("sign_in", { relayUrl, provider })),
	/**
	 *  sign_out — calls POST /auth/device/revoke (best-effort), wipes credentials, transitions to LocalOnly.
	 *  Mirrors the CLI `auth logout` D-10 behavior.
	 */
	signOut: () => typedError<null, string>(__TAURI_INVOKE("sign_out")),
	/**
	 *  retry_auth — bypasses ErrorRecoverable.retry_after_ms and re-attempts the last failing operation.
	 *  For Phase 2 plumbing: resets to LocalOnly and lets the user re-invoke sign_in.
	 *  Phase 3+ will store the last-attempted operation and retry it in place.
	 */
	retryAuth: () => typedError<null, string>(__TAURI_INVOKE("retry_auth")),
	/**
	 *  handle_deeplink — Tauri command for React to invoke when it receives a deep-link URL
	 *  via getCurrent() (cold-start case) or onOpenUrl (fallback for JS-side handling).
	 * 
	 *  Parses the URL, extracts auth params, writes credentials, transitions state,
	 *  and spawns WS client.
	 */
	handleDeeplink: (url: string) => typedError<null, string>(__TAURI_INVOKE("handle_deeplink", { url })),
	/**
	 *  pair_via_ssh — SSH into a remote machine, install cinch, and run
	 *  `cinch auth login --headless` so the remote authenticates independently.
	 * 
	 *  When the remote emits the `<<CINCH-DEVICE-CODE>>` marker, this command
	 *  fires a `SshPairMarkerFound` event carrying the verification URL so the
	 *  frontend can open the browser. The command then blocks until the SSH
	 *  process exits (i.e., until the remote device completes OAuth and
	 *  registers its public key with the relay).
	 */
	pairViaSsh: (target: string, relayUrl: string | null, skipInstall: boolean) => typedError<null, string>(__TAURI_INVOKE("pair_via_ssh", { target, relayUrl, skipInstall })),
	// list_ssh_hosts — return concrete aliases from the user's ~/.ssh/config.
	listSshHosts: () => typedError<string[], string>(__TAURI_INVOKE("list_ssh_hosts")),
	/**
	 *  Pair with a relay using a master token obtained from `cinch auth login`.
	 *  Clears any existing relay and replaces it with the new one.
	 */
	pairWithToken: (req: PairWithTokenRequest) => typedError<PairWithTokenResult, string>(__TAURI_INVOKE("pair_with_token", { req })),
};

/** Events */
export const events = {
	authAdoptedFromCli: makeEvent<AuthAdoptedFromCli>("auth-adopted-from-cli"),
	authStateChanged: makeEvent<AuthStateChanged>("auth-state-changed"),
	cliHandoffRequested: makeEvent<CliHandoffRequested>("cli-handoff-requested"),
	clipDeleted: makeEvent<ClipDeleted>("clip-deleted"),
	clipReceived: makeEvent<ClipReceived>("clip-received"),
	imageDownloadComplete: makeEvent<ImageDownloadComplete>("image-download-complete"),
	imageDownloadFailed: makeEvent<ImageDownloadFailed>("image-download-failed"),
	newSourceDetected: makeEvent<NewSourceDetected>("new-source-detected"),
	offlineQueueDropped: makeEvent<OfflineQueueDropped>("offline-queue-dropped"),
	sshPairMarkerFound: makeEvent<SshPairMarkerFound>("ssh-pair-marker-found"),
	wsStatus: makeEvent<WsStatus>("ws-status"),
};

/* Types */
/**
 *  Fired when the desktop notices that credentials on disk came from the CLI
 *  (the FS watcher observed a credential_version bump while the desktop was
 *  in LocalOnly). The frontend uses this to surface a one-shot toast so the
 *  user knows their CLI sign-in carried over.
 */
export type AuthAdoptedFromCli = {
	user_short: string,
};

export type AuthErrorReason = { kind: "RelayUnreachable" } | { kind: "KeyringUnavailable" } | { kind: "NetworkDown" } | { kind: "InvalidPairToken" };

export type AuthProgress = { kind: "SigningIn" } | { kind: "Pairing" } | { kind: "RotatingToken" };

export type AuthState = { variant: "LocalOnly" } | { variant: "Authenticating"; payload: {
	progress: AuthProgress,
} } | { variant: "Authenticated"; payload: {
	user_id: string,
	device_id: string,
	hostname: string,
	relay_url: string,
	active_relay_id: string,
} } | { variant: "ErrorRecoverable"; payload: {
	reason: AuthErrorReason,
	retry_after_ms: number | null,
} };

export type AuthStateChanged = AuthState;

/**
 *  Fired when the desktop receives a `cinch://login?relay=…&from=cli` deep
 *  link from the CLI's handoff. The React layer responds by opening the
 *  AddRelayDialog with the relay URL pre-filled.
 */
export type CliHandoffRequested = {
	relay_url: string,
};

export type ClipDeleted = string;

export type ClipReceived = LocalClip;

export type ConfigInfo = {
	relay_url: string,
	user_id: string,
	hostname: string,
};

export type Device = {
	id?: string,
	hostname?: string,
	source_key?: string,
	clip_count?: number,
	paired_at?: string,
	last_push_at?: string | null,
	online?: boolean,
	nickname?: string,
	public_key?: string,
	public_key_fingerprint?: string,
};

export type ImageDownloadComplete = string;

export type ImageDownloadFailed = string;

export type LocalClip = {
	id: string,
	user_id: string,
	content: string,
	content_type: string,
	source: string,
	label: string,
	byte_size: number,
	media_path: string | null,
	created_at: number,
	synced: boolean,
	is_pinned: boolean,
	pin_note: string | null,
	received_at: number,
};

export type NewSourceDetected = string;

/**
 *  Fired when queued offline clips are dropped because the encryption key
 *  is missing. The frontend shows a toast prompting the user to sign in again.
 */
export type OfflineQueueDropped = {
	count: number,
};

export type PairWithTokenRequest = {
	relay_url: string,
	pair_token: string,
	label: string | null,
};

export type PairWithTokenResult = {
	relay_id: string,
	user_id: string,
	device_id: string,
};

/**
 *  Settings-pane retention config (plan 01-06).
 * 
 *  `local_days` = rolling window for the local SQLite cache.
 *  `remote_days` = rolling window for relay-stored clips.
 *  Default is 30 days per D-05; clamp range is `[7, 365]` per V5.
 */
export type RetentionConfig = {
	local_days: number,
	remote_days: number,
};

export type SourceAlertSetting = {
	source: string,
	alert_enabled: boolean,
};

export type SourceInfo = {
	source: string,
	clip_count: number,
	last_seen: number,
};

export type SourceSetting = {
	source: string,
	auto_copy: boolean,
};

/**
 *  Fired by `pair_via_ssh` when the remote machine's `cinch auth login
 *  --headless` emits the device-code marker. The frontend opens `url`
 *  in a browser so the user can complete OAuth; the command keeps running
 *  until the SSH process exits.
 */
export type SshPairMarkerFound = {
	url: string,
};

export type WsStatus = string;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

